[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "my_project"
version = "0.0.1"
description = ""

[tool.hatch.build.targets.wheel]
packages = [ "my_project", "emote"]
[tool.hatch.version]
